# Generated by Django 4.2.13 on 2024-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_games_alter_product_category_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='games',
            field=models.ManyToManyField(related_name='players_settings', to='game.games'),
        ),
    ]
