# Generated by Django 4.2.13 on 2024-06-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_players_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=250)),
                ('long_text', models.TextField()),
                ('numder', models.IntegerField()),
                ('float_numder', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('true_or_false', models.BooleanField(default=False)),
                ('many_to_many', models.ManyToManyField(related_name='many_to_many', to='game.games')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='one_to_many', to='game.games')),
            ],
        ),
    ]
